// import './01-practica/101.big.js';
// import './01-practica/102.califications.js';
// import './01-practica/103.checkArguments';
// import './01-practica/104.clone-merge.js';
// import './01-practica/105.deeep-equal.js';
import './01-practica/106.dices.js';
import './01-practica/107.hoisting.js';
// import './01-practica/108.Includes.js';
// import './01-practica/114.values.js';
// import './01-practica/111.reverse-text.js';
// import './01-practica/112.subsets.js';
// import './01-practica/113.this.js';
// import './02-entregables/ejercicio-01.js';
// import './02-entregables/ejercicio-02.js';
// import './02-entregables/ejercicio-03.js';
// import './02-entregables/ejercicio-04.js';
// import './02-entregables/ejercicio-05.js';
// import './03-retos/control-traces.js';
// import './03-retos/flatten-array.js';
// import './03-retos/memoization.js';
// console.log('Welcome to Exercises Playground.');
